// Package chunking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package chunking

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Chunk A chunk of text with position information.
type Chunk struct {
	// EndChar Character position in original text where chunk ends (exclusive)
	EndChar int `json:"end_char"`

	// Id Sequence number of the chunk (0, 1, 2, ...)
	Id uint32 `json:"id"`

	// StartChar Character position in original text where chunk starts
	StartChar int `json:"start_char"`

	// Text The chunk content
	Text string `json:"text"`
}

// ChunkOptions Per-request configuration for chunking. All fields are optional - zero/omitted values use chunker defaults.
type ChunkOptions struct {
	// MaxChunks Maximum number of chunks to generate per document.
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// OverlapTokens Number of tokens to overlap between consecutive chunks. Helps maintain context across chunk boundaries. Only used by fixed-size chunkers.
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Separator string for splitting (e.g., '\n\n' for paragraphs). Only used by fixed-size chunkers.
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk.
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Minimum confidence threshold for separator detection (0.0-1.0). Only used by ONNX models.
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUQW/zNgz9K4QuXwo4Wtrecit62aXtgPUwYBkKxaJtrbLkklSatsh/HyS7adZ4hwHf",
	"zRapx/fIR32oOvZDDBiE1fpDcd1hb8rnbZfCc/6wyDW5QVwMaq1uoM4BiA0I7gVenXQwRHY5Di40kXqT",
	"v7Wq1EBxQBKHBRGDfao7Q+egt50hUwvSKRJEcq0Lxk+FOiScimOwDAvc1z6x2+GFqpS8DajWygXBFkkd",
	"KuXseaHf8SVhqBFC6rdIRUX3ibpYVXBZwVUFWusZzErtl21cTqfJBbm+yoVYDMlPUlaweFZPzj0v8Hik",
	"X8cgGOTrLgu50KrDoVKEL8kRWrX+M/dlAvsX9eprPn8dIeL2b6wlVy92eChV+ZzFb0jLXANZMo/GtYmK",
	"C6CJNPJzodVw4z00Dr1lMIQQy33jYQnvSPGX2DsRtLAzPiFD4kkbElhsTPLC57bqzf6pZM3wujN716f+",
	"ZNxjJkiEFgOSEYQhw8c69RhEz7Y+7pC8GZ4kPuOc/PsvN5WMDD/dgS3KK2LIbWGsk7jdJIo1/Ip+YOiN",
	"C2JcGCe4FzA1ReZprNuYgjXkkDU8BP+Wu2Jh+waN26Ndsns/Nonn2TMOhoxEmtuHKQSjWcq4ePBOJP8t",
	"ULe6gh+bTdhswo8SzRdaMkPHF/+L0KcbKyWGWpT/bOZjCZ9u6NjTPKaCO69SOkLuop/Z+jsXiguKM23Z",
	"/2P2qPjYBouCdTHuYqVXy0u9+q7y4f7+D+ijRV/Uje+dWqvGR3OyfCP9snzfdikf5XdyZhqdIbSQ87nw",
	"Km44bk8Gd+KxPCvjGTzmXFWpHRKPICu90pfFtAMGMzi1Vtd6pa/z3hjpWK1D8v7wTwAAAP//NbrQEfoF",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
