// Package logging provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package logging

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for Level.
const (
	LevelDebug Level = "debug"
	LevelError Level = "error"
	LevelInfo  Level = "info"
	LevelWarn  Level = "warn"
)

// Defines values for Style.
const (
	StyleJson     Style = "json"
	StyleLogfmt   Style = "logfmt"
	StyleNoop     Style = "noop"
	StyleTerminal Style = "terminal"
)

// Config Logging configuration for Termite services
type Config struct {
	// Level Logging verbosity level
	Level Level `json:"level,omitempty,omitzero"`

	// Style Logging output format style. 'terminal' for colorized console, 'json' for structured JSON, 'logfmt' for token-efficient key=value pairs, 'noop' for silent.
	Style Style `json:"style,omitempty,omitzero"`
}

// Level Logging verbosity level
type Level string

// Style Logging output format style. 'terminal' for colorized console, 'json' for structured JSON, 'logfmt' for token-efficient key=value pairs, 'noop' for silent.
type Style string

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4xSzY4TMQx+lcgg9RK1rPY2N7Q3VMGh3BCHNOOZZpWJI8cZKKu+O3LaYQdEBbco/uzv",
	"x34BT1OmhEkKdC9Q/Akn155PlIYw6qvH4jlkCZSggz2NY0ij8a1e2em/GYjNZ+QpCJqCPAePBSxkpows",
	"AdvIiDNGfbxlHKCDN7tX9t2NerdvoIuFIueI/0IfGuhysSDnjNABHZ/Ri/bvF7YeB1ejQAchDQT2jqEZ",
	"+UglyNlcdVrAVCfovkCPxzqCXdq/OU5aZSaGrxbwu5uySl0ANylFOKRRpRwWK69SRMNKLt6VQ1VyFQ12",
	"cmJaGFuzWdo2LXFPkTj8wF63USiiNZvnQulaLcLVS2XszYfDp4/WbBJRvtVCxCTblcmVIB0BFhT9u78V",
	"5g+PuoHm/j/v5bq/v56NipIgjfB9kiGef0GWWU/rWWBhRi5XtvnBxXxyD5o6ZUwuB+jgcftu+6jn6ORU",
	"oEs1xsvPAAAA//9B6Wt3+wIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
