// Package scraping provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package scraping

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ContentSecurityConfig defines model for ContentSecurityConfig.
type ContentSecurityConfig struct {
	// AllowedHosts Whitelist of allowed hostnames/IPs for link downloads. If empty, all hosts are allowed (except private IPs if block_private_ips is true).
	AllowedHosts []string `json:"allowed_hosts,omitempty,omitzero"`

	// BlockPrivateIps Block requests to private IP ranges (127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16)
	BlockPrivateIps bool `json:"block_private_ips,omitempty,omitzero"`

	// DownloadTimeoutSeconds Timeout for individual download operations in seconds
	DownloadTimeoutSeconds int `json:"download_timeout_seconds,omitempty,omitzero"`

	// MaxDownloadSizeBytes Maximum size of downloaded content in bytes
	MaxDownloadSizeBytes int64 `json:"max_download_size_bytes,omitempty,omitzero"`

	// MaxImageDimension Maximum image width/height in pixels (images will be resized)
	MaxImageDimension int `json:"max_image_dimension,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/3yUzW7jOAzHX4XgqQVc107TNPVxe+phgQW6wB4WA0OxGYdTfY1EN8kUffeB7CR1Gswg",
	"F5Em//nxQ3rHxhnvLFmJWL1jbDZk1HB8clbIygs1fWDZPzm75i598MF5CsI0hCmt3ZbaeuPiKNFSbAJ7",
	"YWexwv82LKQ5Crg1HGIhxVplKN4+/xNh7QJotq/Quq3VTrUxh+c1kPGyz1LOEB9BBTopXNGuIS/gA78p",
	"IUg6vIaVds1rfXDW7CNwBAk9XeeYIe2U8Zqw+v94zBtnMMOmtfm5p3yc5UU+y0v8liELmaE02XvCCqME",
	"th1+ZEeHCkHtk33x/2ND1qrXglUCyb7056+UAYF+9JRqFDcpCYKyHUW4KmcPeZF+t8sMymJyfpjl5WKw",
	"ylkGibpcLEd7kUG5eMxn9/ODfY0n4JVzmpRNyMem18KGXC91pMbZ9pz8rvjK/e8YPQyPbctv3PZKn0YI",
	"aUVUio3AFo6akxkkScOWTW+wKk9kbIU6ConMqF19oov8k+rVXugcrCzmy/uHRXHB97faJWlIeWn1jkLU",
	"QjMuduIaBSdUE70TXHEBl+HupnM3n97F/AjMRnVUt2zIxoFkAjsr5svfcQ55sOVWNrcb4m4z8HnekY5w",
	"NXyNsGWtYUUQKJXVXk/JR/E/dfRzX93qOzWCH8nFdu0ur+142/txhDC+CsOsj82Lh2cBlG0/px5JhG0X",
	"020TlsSFL01Qnm0HZ5qY4RuFsUWY9rlMHXSerPKMFd7lRX6HGXolm4iV7bX++BUAAP//pHRAPa0EAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
