// Package scraping provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package scraping

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ContentSecurityConfig defines model for ContentSecurityConfig.
type ContentSecurityConfig struct {
	// AllowedHosts Whitelist of allowed hostnames/IPs for link downloads. If empty, all hosts are allowed (except private IPs if block_private_ips is true).
	AllowedHosts []string `json:"allowed_hosts,omitempty,omitzero"`

	// AllowedPaths Whitelist of allowed path prefixes for file:// and s3:// URLs. If empty, all paths are allowed. For file:// use absolute paths (e.g., /Users/data/). For s3:// use bucket/prefix (e.g., my-bucket/uploads/).
	AllowedPaths []string `json:"allowed_paths,omitempty,omitzero"`

	// BlockPrivateIps Block requests to private IP ranges (127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16)
	BlockPrivateIps bool `json:"block_private_ips,omitempty,omitzero"`

	// DownloadTimeoutSeconds Timeout for individual download operations in seconds
	DownloadTimeoutSeconds int `json:"download_timeout_seconds,omitempty,omitzero"`

	// MaxDownloadSizeBytes Maximum size of downloaded content in bytes
	MaxDownloadSizeBytes int64 `json:"max_download_size_bytes,omitempty,omitzero"`

	// MaxImageDimension Maximum image width/height in pixels (images will be resized)
	MaxImageDimension int `json:"max_image_dimension,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5SUz27jNhDGX2XAkw0o+mM7jqNjAxQI0AJF06CHohBoaSRPQ5EsOYrtDfLuC0qWI8fY",
	"xS50IUczn376Zsg3UZrWGo2avcjfhC932Mp++WA0o+YnLDtHfHwwuqYmvLDOWHRM2KdJpcweq2Jn/CBR",
	"oS8dWSajRS7+3hGjIs9gajjlQsjVskWfPP7hoTYOFOkXqMxeKyMrH8NjDdhaPkahps/3IB2eFWZ4KNEy",
	"WEevkhGCDtWwVaZ8KU7BgqwH8sCuw3ksIoEH2VqFIv9nXMalaUUkykrHl5HsfhGn8SLOxL+RIMa2/zU+",
	"WhS58OxIN+I9GgPSOXkM+9EMK3n3o2aEXLAOazrgYEZNCvMkAakr8Muwev7ztytT+m9MTYnh10lx5xHk",
	"1hvVMZ5yZxg3cQTJs0fnk0qyTOZD0fCVULLtyhfkZOAZK9rjzSne2b5ByWc/p5oiEtcFP+fjVR8HL2vZ",
	"KRZ5aGj0ydpfQgU4/L/DMCtsJqMBTuoGPcyyxV2chifZRJClk/XdIs7W/S5bRBC6n603w34dQba+jxe3",
	"q9N+Ls7AW2MUSh2Qx+EtmFo0HRceS6OrS/Jl+pn7ryG77zvpil6p6qQ6HwUIR02GXA+kYdSceB8kW9LU",
	"dq3IszMZacYGXSBr5aE403n6gsX2yHgJlqWrze3dOr3i+10egjSEujC1oxBWUA4XROAaBCdUE70zXHoF",
	"F4nDTWNuPqLr1QhMrWywqKhF7XuSCewiXW2+xdnXwZ4q3iU7pGbX81k6oPIw69962JNSsEVwGH6rmk/J",
	"B/HvOfoxr2b7H5Ys3kOIdG2uT/xwa3ZDC2G4Xftej+b50/XaH/Zz1z0yk258OGVMHLjEU+mkJd3AhaaI",
	"xCu6wSIR5jkLDhqLWloSuVjGabwUkTjdSLpT6v1rAAAA//81U/1/9QUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
